# This workflow is intended to automate the process of code merging after a Pull Request has been approved
name: Pull Request Automerge

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

env:
  PR_URL: ${{github.event.pull_request.html_url}}

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Enable auto-merge
      run: gh pr merge --auto --merge --delete-branch "$PR_URL"
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
