name: Staging
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  prepare_simulator:
    name: Prepare iOS Simulator
    runs-on: macOS-latest
    outputs:
      device_id: ${{ steps.simulator_device.outputs.iphone_id }}
    steps:
      - name: Create iOS Simulator
        id: simulator_device
        run: |
          xcrun simctl list runtimes
          xcrun simctl list devicetypes
          echo creating device
          xcrun simctl create "iPhone 12 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro com.apple.CoreSimulator.SimRuntime.iOS-15-2
          echo "::set-output name=iphone_id::$(xcrun simctl create "iPhone 12 Pro" com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro com.apple.CoreSimulator.SimRuntime.iOS-15-2)"
          xcrun simctl list devices
  build:
    name: Build Project
    needs: prepare_simulator
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
          -scheme ParadiseOnCombine \
          -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" \
  test:
    name: Test Project
    needs: [prepare_simulator, build]
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1

      - name: Test
        run: |
          xcodebuild \
          -allowProvisioningUpdates \
          -project ParadiseOnCombine.xcodeproj \
          -scheme ParadiseOnCombineTests \
          -destination platform=macOS,arch=x86_64 \
          test \
