name: Staging
on:
  push:
    branches:
      - dev
      - main 
  pull_request:
    branches:
      - dev
      - main

jobs:
#  build:
#    name: Build Project
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v1
#
#      - name: Setup Xcode version
#        uses: maxim-lobanov/setup-xcode@v1.4.1
#
#      - name: Build
#        run: |
#          set -o pipefail
#          xcodebuild build \
#          -scheme ParadiseOnCombine \
#          -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" \
  test:
    name: Test Project
#    needs: build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1

      - name: Test
        run: |
          xcodebuild \
          -allowProvisioningUpdates \
          -scheme ParadiseOnCombine \
          -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" \
          test \
