name: Staging
on:
  push:
    branches:
      - dev
      - main 
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with: 
          xcode-version: 13.2.1
      
      - name: List devices available
        run: |
          xcrun simctl list \
        
      - name: Build
        run: |
          xcodebuild \
          -scheme ParadiseOnCombine \
          -sdk iphonesimulator15.2 \
          -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" \
          build \
  test:
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1

      - name: Test
        run: |
          xcodebuild \
          -allowProvisioningUpdates \
          -scheme ParadiseOnCombine \
          -destination "platform=iOS Simulator,name=iPhone 12,OS=15.2" \
          test \
